sudo: required
language: ruby

matrix:
  include:
    #Run sanity tests on gem without development dependencies
    - rvm: 2.2.4
      env: installed=1 gem_sanity=1 docker_ver=1.12.3
      services: docker
    #Run fast tests on working copy
    - rvm: 2.2.4
      env: installed=0 fast=1 docker_ver=1.12.3
      services: docker
    #Run fast tests for installed gem on different ruby
    #versions and the latest docker
    - rvm: 2.0.0
      env: installed=1 fast=1 docker_ver=1.12.3
      services: docker
    - rvm: 2.1.8
      env: installed=1 fast=1 docker_ver=1.12.3
      services: docker
    - rvm: 2.2.4
      env: installed=1 fast=1 docker_ver=1.12.3
      services: docker
    - rvm: 2.3.0
      env: installed=1 fast=1 docker_ver=1.12.3
      services: docker
    #Run fast tests for installed gem on older docker versions
    - rvm: 2.2.4
      env: installed=1 fast=1 docker_ver=1.9
      services: docker
    - rvm: 2.2.4
      env: installed=1 fast=1 docker_ver=1.10
      services: docker
    - rvm: 2.2.4
      env: installed=1 fast=1 docker_ver=1.11
      services: docker
    #Run long running tests for installed gem on
    #one specific docker/ruby version pair
    - rvm: 2.2.4
      env: installed=1 slow=1 docker_ver=1.12.3
      services: docker

notifications:
  email:
    - rbld-devel@rbld.io

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine="${docker_ver}*"

install: ./tools/travis-install.sh
script: ./tools/travis-run.sh
